version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: monthly
  reviewers:
    - "buildkite/agent-stewards"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
